#聚合数据短信配置
sms:
  juhe:
    appKey: 1f5fb999eb9376d5df96bf8bd26626a5
    url: http://v.juhe.cn/sms/send
#网关数据接口
gateway:
  url: http://10.154.6.51:23334/
  api: http://10.154.6.51:23334/WebService/
#车好运验证地址
chy:
  url: http://123.207.179.214/ajwl/login.verifyUser.action
  user.account: cl
  user.password: e10adc3949ba59abbe56e057f20f883e
#大数据平台监控
bigdata:
  url: http://115.159.191.206:7180/cmf/login
  username: admin
  password: pass@word1
#极光推送
jpush:
  driver: #司机端
    appkey: c34d408b9db8016ef8aeea2b
    secret: 897c0982c0ea58315fa0b9ca
  admin: #管理端
    appkey: 3b0dc7773970a77ed8f2be8a
    secret: ad5419580feb592890bd1d5a
  carrier: #承运端
    appkey: 8361c73ab23f2d1aa616eabd
    secret: ed0ae8606026fa582f25de4a
#============================================================================
# netty socket io setting
#============================================================================
# host在本地测试可以设置为localhost或者本机IP，在Linux服务器跑可换成服务器IP
# SocketIO配置
socketio:
    # SocketIO端口
    port: 9090
    # 连接数大小
    workCount: 100
    # 允许客户请求
    allowCustomRequests: true
    # 协议升级超时时间(毫秒)，默认10秒，HTTP握手升级为ws协议超时时间
    upgradeTimeout: 10000
    # Ping消息超时时间(毫秒)，默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
    pingTimeout: 60000
    # Ping消息间隔(毫秒)，默认25秒。客户端向服务器发送一条心跳消息间隔
    pingInterval: 25000
    # 设置HTTP交互最大内容长度
    maxHttpContentLength: 1048576
    # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
    maxFramePayloadLength: 1048576
#高德地图相关
amap:
  gaoDeKey: 2ea0fdea7b79f5794e9d88420ab12e38
  locationUrl: https://restapi.amap.com/v3/geocode/regeo
bigData:
  url: http://123.206.124.38:8082/
company:
  pid: 5937609886053550
