spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.206.212.190:3306/navinfo-test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: dbManager
    password: Chy@2017
    #driver-class-name: com.ibm.db2.jcc.DB2Driver
    #url: jdbc:db2://115.159.203.24:50000/HSAE_DB
    #username: db2inst1
    #password: hsae@1706
    druid: # 下面为连接池的补充设置，应用到上面所有数据源中
      initial-size: 5  # 初始化大小，最小，最大
      min-idle: 5
      max-active: 20
      max-wait: 60000 # 配置获取连接等待超时的时间
      pool-prepared-statements: false # 打开PSCache，并且指定每个连接上PSCache的大小 MySQL下建议关闭
      max-pool-prepared-statement-per-connection-size: 100
      max-open-prepared-statement: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30
      test-on-query: false
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  # 配置一个连接在池中最小生存的时间，单位是毫秒
      filters: stat,wall,slf4j,log4j   # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      ######Druid监控配置######
      #是否启用StatFilter默认值true
      #哪些资源配置监控：主要只静态资源和监控地址本身
      web-stat-filter:
        enable: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        #IP 白名单
        #allow: 127.0.0.1
        #IP 黑名单
        # deny: 
        enable: true 
        url-pattern: /druid/*
        login-username: druid  #druid控制台的用户名与密码
        login-password: 123456
        reset-enable: false #禁止手动重置监控数据
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000   # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
